'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{spawn}=require('child_process');
async function build(local){
 const mac=process.platform==='darwin',source=path.join(__dirname,'scripts',mac?'codex-dial-macos.m':'codex-dial-windows.cs');
 const hash=crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex').slice(0,16),bundled=path.join(process.env.YOGO_RUNTIME_DIR||path.join(__dirname,'runtime'),mac?'codex-dial-macos':'codex-dial-windows.exe');if(fs.existsSync(bundled))return bundled;
 const exe=path.join(local,`codex-dial-${process.platform}-${process.arch}-${hash}${mac?'':'.exe'}`);if(fs.existsSync(exe))return exe;if(!['darwin','win32'].includes(process.platform))throw new Error('波轮控制仅支持 Windows 和 macOS');
 const windows=process.env.SystemRoot||'C:\\Windows',compiler=mac?'/usr/bin/clang':['Framework64','Framework'].map(p=>path.join(windows,'Microsoft.NET',p,'v4.0.30319','csc.exe')).find(p=>fs.existsSync(p));if(!compiler)throw new Error(mac?'找不到 macOS 编译器':'波轮控制需要 Windows .NET Framework 4.x');
 const temp=exe+'.'+process.pid+(mac?'':'.exe'),args=mac?['-fobjc-arc','-framework','AppKit','-framework','ApplicationServices',source,'-o',temp]:['/nologo','/target:exe','/optimize+','/reference:System.Web.Extensions.dll','/reference:UIAutomationClient.dll','/reference:UIAutomationTypes.dll','/reference:WindowsBase.dll','/lib:'+path.join(path.dirname(compiler),'WPF'),'/out:'+temp,source];
 await new Promise((resolve,reject)=>{const c=spawn(compiler,args,{windowsHide:true,stdio:['ignore','pipe','pipe']});let output='';const timer=setTimeout(()=>{c.kill();reject(new Error('波轮控制组件编译超时'));},20000);c.stdout.on('data',d=>output=(output+d).slice(-2000));c.stderr.on('data',d=>output=(output+d).slice(-2000));c.on('error',e=>{clearTimeout(timer);reject(e);});c.on('exit',code=>{clearTimeout(timer);code===0?resolve():reject(new Error('波轮控制组件编译失败：'+output));});});
 try{fs.renameSync(temp,exe);}catch(e){if(!fs.existsSync(exe))throw e;fs.unlinkSync(temp);}return exe;
}
class CodexDial{
 constructor(local,changed=()=>{}){this.local=local;this.changed=changed;this.child=null;this.closed=false;this.retry=null;this.info={enabled:true,ready:false,lastAction:null,error:null,keys:'- / = → Codex 原生命令',hardwareKeys:'- / =',warning:process.platform==='darwin'?'先检查 Codex 快捷键：Control+Option+Shift+- 降低、Control+Option+Shift+= 提高；未绑定时手动设置':'Windows 首次需在 Codex 手动绑定：Ctrl+Alt+Shift+- 降低、Ctrl+Alt+Shift+= 提高'};}
 snapshot(){return {...this.info};}
 async start(){if(this.closed)return;try{const exe=await build(this.local);if(this.closed)return;const child=spawn(exe,[],{windowsHide:true,stdio:['ignore','pipe','pipe']});this.child=child;child.stdout.setEncoding("utf8");let buffer='',ended=false,helperError=null;const failed=message=>{if(ended)return;ended=true;if(this.child===child)this.child=null;child.kill();if(!this.closed){this.info.ready=false;this.info.error=message;this.changed();this.retry=setTimeout(()=>this.start(),10000);}};child.stdout.on('data',chunk=>{buffer+=chunk;if(buffer.length>65536){failed('波轮控制数据异常');return;}let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);try{const event=JSON.parse(line);if(event.protocol!==1)throw new Error();if(event.type==='ready'){this.info.ready=true;this.info.error=null;}else if(event.type==='adjust'){this.info.lastAction=event.detail;this.info.error=null;}else if(event.type==='error'){helperError=event.detail;this.info.error=event.detail;}this.changed(event);}catch{failed('波轮控制协议异常');return;}}});child.stderr.on('data',()=>{});child.on('error',e=>failed(e.message));child.on('exit',code=>failed(helperError||(code===0?'波轮控制进程已退出':'波轮控制进程异常退出')));}catch(e){if(!this.closed){this.info.error=e.message;this.changed();this.retry=setTimeout(()=>this.start(),10000);}}}
 close(){this.closed=true;clearTimeout(this.retry);this.child?.kill();this.child=null;}
}
module.exports={CodexDial,build};
