'use strict';
const $=id=>document.getElementById(id),all=s=>[...document.querySelectorAll(s)];
const icons={grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/><path d="m20 2 .6 1.4L22 4l-1.4.6L20 6l-.6-1.4L18 4l1.4-.6Z"/>',dial:'<circle cx="12" cy="12" r="8"/><path d="m12 12 4-4M4 3 2 6m18-3 2 3"/>',mic:'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8"/>',check:'<path d="m5 12 4 4L19 6"/><path d="M21 12a9 9 0 1 1-9-9"/>',settings:'<path d="m10 3-1 3-3 1-3 3 2 3-1 3 3 3 3-1 3 2 3-2 3-1 1-4-2-3 1-3-3-3-3 1Z"/><circle cx="12" cy="12" r="3"/>',keyboard:'<rect x="2" y="5" width="20" height="14" rx="2"/><path d="M6 9h1m3 0h1m3 0h1m3 0h1M6 12h1m3 0h1m3 0h1m3 0h1M7 16h10"/>',refresh:'<path d="M20 10a8 8 0 1 0-2 8M20 3v7h-7"/>',sliders:'<path d="M4 7h8m4 0h4M4 17h3m4 0h9"/><circle cx="14" cy="7" r="2"/><circle cx="9" cy="17" r="2"/>',plug:'<path d="M8 3v5m8-5v5M6 8h12v3a6 6 0 0 1-12 0Zm6 9v5"/>',activity:'<path d="M3 12h4l3-8 4 16 3-8h4"/>',pause:'<path d="M8 5v14M16 5v14"/>',play:'<path d="m8 4 12 8-12 8Z"/>',upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>',shield:'<path d="m12 2 8 3v6c0 5-4 8-8 11-4-3-8-6-8-11V5Z"/><path d="m8 12 3 3 5-6"/>',cross:'<path d="m6 6 12 12M6 18 18 6"/>',question:'<path d="M8 7a4 4 0 1 1 6 4c-2 1-2 2-2 4m0 4v.1"/>',ring:'<path d="M20 12a8 8 0 1 1-8-8"/><circle cx="19" cy="6" r="1"/>'};
const svg=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.spark}</svg>`;
all('[data-icon]').forEach(el=>el.innerHTML=svg(el.dataset.icon));
const effects={busy:{title:'思考 / 执行',name:'蓝色追光',note:'持续转动，专注进行中',description:'任务进行中',icon:'ring',color:'#4b95c8',soft:'#edf5fa'},done:{title:'执行完成',name:'绿色对勾',note:'入场生长，然后轻呼吸',description:'本轮结束，不代表目标已完成。',icon:'check',color:'#739957',soft:'#eef4e6'},error:{title:'执行出错',name:'红色叉号',note:'明确提醒，不错过异常',description:'任务终止出错时提醒。',icon:'cross',color:'#c97762',soft:'#faeee9'},waiting:{title:'等待处理',name:'琥珀色问号',note:'等一个回答，再继续',description:'等待确认或回答。',icon:'question',color:'#b9994a',soft:'#f9f3e3'},voice:{title:'语音波形',name:'绿色波形',note:'说话时，绿色波形随声而动',description:'演示波形。实际随微信输入法收音变化。',icon:'mic',color:'#459767',soft:'#e8f4eb'}};
let appInfo=null,lastStatus=null,library=[],selected='busy',previewStart=performance.now(),currentPage='overview',requestBusy=false,stopped=false;
let toastTimer=null,previewPending=false,pollPending=false,infoPending=false;
function toast(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,error?6500:3500);}
function setText(id,value){if($(id)&&$(id).textContent!==String(value))$(id).textContent=value;}
function go(page){if(page==='voice')page='overview';if(!$("page-"+page))return;currentPage=page;all('.page').forEach(el=>el.classList.toggle('active',el.id==='page-'+page));all('[data-page]').forEach(el=>{const active=el.dataset.page===page;el.classList.toggle('active',active);active?el.setAttribute('aria-current','page'):el.removeAttribute('aria-current');});setText('page-label',{overview:'设备总览',lighting:'点阵与灯效',dial:'波轮与按键',voice:'语音联动',setup:'首次设置',settings:'偏好设置'}[page]);history.replaceState(null,'','#'+page);window.scrollTo({top:0});}
all('[data-page]').forEach(el=>el.onclick=()=>go(el.dataset.page));all('[data-goto]').forEach(el=>el.onclick=()=>go(el.dataset.goto));window.addEventListener('hashchange',()=>go(location.hash.slice(1)));go(location.hash.slice(1)||'overview');
async function request(url,data){const response=await fetch(url,{...(data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Player-Token':token},body:JSON.stringify(data)}),signal:AbortSignal.timeout(15000)});let payload;try{payload=await response.json();}catch{throw Error('本地服务返回了无法识别的响应');}if(!response.ok)throw Error(payload.error||'操作没有完成');return payload;}
async function act(url,data={},message='已完成'){if(requestBusy)return false;requestBusy=true;try{const result=await request(url,data);updateStatus(result);await refreshInfo();if(message)toast(message);return true;}catch(error){toast(friendlyError(error.message),true);return false;}finally{requestBusy=false;}}
function friendlyError(message){if(/Expected one .*found 0/.test(message))return '未找到键盘。请接入接收器或 USB 数据线，并唤醒键盘。';if(/Expected one .*found/.test(message))return '检测到多把同类设备，请只保留一把需要设置的键盘。';if(/Failed to fetch|fetch failed/.test(message))return '本地服务未连接，请重新启动 YOGO Studio。';if(/No acknowledgement/.test(message))return '键盘暂未响应，请检查电量、连接模式和接收器。';return message;}
function theme(value){document.documentElement.dataset.theme=value==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value;}
matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(appInfo?.settings.theme==='system')theme('system');});
function applyInfo(info){appInfo=info;const count=info.devices.length,connected=count>0;document.body.classList.toggle('connected',connected);$('connection-notice').hidden=connected&&!info.deviceError;
if(count>1){$('connection-notice').hidden=false;$('connection-notice').querySelector('strong').textContent='检测到多个键盘接口';$('connection-notice').querySelector(':scope > div > span').textContent='请只保留目标键盘，再进行板载设置。';}
else {$('connection-notice').querySelector('strong').textContent='连接你的 YOGO 75 PRO';$('connection-notice').querySelector(':scope > div > span').textContent=info.deviceError||'USB / 2.4G 连接后唤醒键盘。';}
setText('sidebar-connection',connected?info.devices[0].transport:'未检测到设备');$('hero-connection').classList.toggle('good',connected);$('hero-connection').replaceChildren();const dot=document.createElement('i');$('hero-connection').append(dot,document.createTextNode(connected?info.devices[0].transport+' · 已识别':'尚未连接'));
all('.requires-device').forEach(el=>{el.disabled=count!==1;el.title=count===1?'':'请先连接一把受支持的键盘';});
const s=info.settings;all('[data-setting]').forEach(el=>el.setAttribute('aria-checked',String(!!s[el.dataset.setting])));$('theme').value=s.theme||'light';theme(s.theme||'light');document.documentElement.classList.toggle('reduce-motion',!!s.reduceMotion);
if(![...$('duration').options].some(o=>Number(o.value)===s.resultDisplayMs))$('duration').add(new Option((s.resultDisplayMs/1000)+' 秒',String(s.resultDisplayMs)));$('duration').value=String(s.resultDisplayMs);
all('[data-map]').forEach(el=>el.value=s.stateAnimations[el.dataset.map]||el.dataset.map);
const mac=info.platform==='darwin';$('mac-permission-step').hidden=!mac;setText('hooks-step-number',mac?'05':'04');all('.shortcut-decrease').forEach(el=>el.textContent=mac?'⌃ Control + ⌥ Option + ⇧ Shift + −':'Ctrl + Alt + Shift + −');all('.shortcut-increase').forEach(el=>el.textContent=mac?'⌃ Control + ⌥ Option + ⇧ Shift + =':'Ctrl + Alt + Shift + =');
setText('dial-binding-title',mac?'Mac 首次使用先检查快捷键':'Windows 首次使用需手动绑定');setText('dial-binding-note',mac?'Codex → 设置 → 键盘快捷键，检查上面两组绑定；已匹配可跳过，未绑定则手动录入。本程序不会自动绑定。':'Codex → 设置 → 键盘快捷键，搜索“推理强度”，用实体键盘录入上面两组组合键。本程序不会自动绑定。');setText('setup-dial-binding',mac?'在 Codex 中检查两项推理强度快捷键；未绑定时需手动设置。':'Windows 首次使用需在 Codex 中手动绑定两项推理强度快捷键。');
const voiceShortcut=mac?'右 Option':'Ctrl + F5';setText('voice-shortcut-hint','首次使用：请在微信输入法设置中，将语音快捷键设为 '+voiceShortcut+'。');setText('setup-voice-binding','首次使用：在微信输入法中将语音快捷键设为 '+voiceShortcut+'，并用官方插件设置自定义键；本程序不会修改自定义键。');
setText('voice-platform-note',mac?'macOS 在微信输入法收音时临时采集默认麦克风来计算音量；需要麦克风权限。':'Windows 读取微信输入法的收音会话和音量，不单独录音。');
setText('setup-device-status',connected?'已识别 · '+info.devices.map(d=>d.transport).join(' / '):'待连接 · 可先预览界面');setText('setup-codex-status',info.sessionsAvailable?'已找到本地任务目录':'尚未找到本地任务目录，请先在 Codex 中运行一次任务');
setText('setup-progress',s.onboardingComplete?'已阅读使用指南':'首次使用指南');all('.setup-dot').forEach(el=>el.hidden=!!s.onboardingComplete);
}
async function refreshInfo(){if(infoPending)return;infoPending=true;try{applyInfo(await request('/app-info'));if(!scopeSelecting){$('scope').value=appInfo.settings.scope||'global';$('session-row').hidden=appInfo.settings.scope!=='current';}}catch(error){toast(friendlyError(error.message),true);}finally{infoPending=false;}}
function updateStatus(data){lastStatus=data;setText('version','v'+data.version);setText('about-version',data.version);setText('service-label','已连接');$('service-alert').hidden=true;const f=data.follow||{},state=f.state||'stopped',auto=data.mode==='auto';
setText('follow-pill',auto?'自动跟随':'已暂停跟随');setText('follow-title',f.error?'任务监听异常':{busy:'任务进行中',waiting:'等你处理',done:'本轮已结束',error:'本轮终止出错',stopped:'待机'}[state]||'等待任务');
setText('follow-detail',f.error||(!auto?'灯效由手动控制，任务状态仍会更新。':state==='busy'?'':state==='waiting'?'完成确认或回答后，联动会继续。':''));
$('status-orb').dataset.state=state;setText('metric-active',f.active??(state==='busy'?1:0));setText('metric-waiting',f.waiting??0);setText('metric-failed',f.failed??(state==='error'?1:0));$('follow-toggle').innerHTML=svg(auto?'pause':'play')+'<span>'+(auto?'暂停跟随':'恢复跟随')+'</span>';
setText('playback-message',data.error?friendlyError(data.error):data.backlightError?'背光暂时停止：'+friendlyError(data.backlightError):data.releasedFor?'提示已结束，已将显示交还键盘。':data.state==='stopped'?'待命中 · 原显示已恢复。绿勾仅表示本轮结束。':data.connection+' · 正在播放'+(effects[data.state]?.name||data.animationId));
const d=data.codexDial||{},v=data.voice||{};const dialText=!d.enabled?'波轮联动已关闭':d.error?'需要处理：'+d.error:d.ready?'波轮监听就绪'+(d.lastAction?' · 最近'+d.lastAction:''):'波轮组件启动中';setText('dial-live-status',dialText);setText('dial-summary',!d.enabled?'已关闭 · 可随时开启':d.ready?'监听就绪 · 仅作用于 Codex':'需要完成设置');
setText('voice-summary',!v.enabled?'语音联动已关闭':v.error?'语音监听需要处理':v.active?(v.providerName||'语音来源')+'正在收音':'监听待命');setText('voice-title',!v.enabled?'语音联动已关闭':v.error?'语音监听需要处理':v.active?'正在听你的灵感':'等待语音输入');setText('voice-detail',v.error||(!v.enabled?'开启下方开关，让波形跟随语音输入。':v.active?'收音结束后，自动恢复最新的任务状态。':'启用微信输入法的语音输入后，灯效会自动跟随。'));setText('voice-pill',v.active?(v.levelKind==='unavailable'?'正在收音 · 音量不可用':'正在收音 · 实时音量'):v.enabled?'监听待命':'已关闭');
$('animation-errors').hidden=!data.animationErrors?.length;if(data.animationErrors?.length)setText('animation-errors',data.animationErrors.join('；'));
}
async function poll(){if(pollPending||stopped)return;pollPending=true;try{updateStatus(await request('/status'));}catch{setText('service-label','未连接');$('service-alert').hidden=false;setText('service-alert','本地服务已断开，显示的状态可能已过期。请重新启动应用。');all('.requires-device').forEach(el=>el.disabled=true);}finally{pollPending=false;}}
for(let i=0;i<36;i++){const pixel=document.createElement('i');pixel.className='pixel';$('large-matrix').append(pixel);}
function selectEffect(id){selected=id;previewStart=performance.now();const info=effects[id]||{name:library.find(a=>a.id===id)?.name||id,description:'自定义像素动画。仅在预览中播放，不会接管真实键盘。'};setText('selected-name',info.name);setText('selected-description',info.description);setText('hero-effect-name',info.name);all('[data-effect]').forEach(el=>{el.classList.toggle('selected',el.dataset.effect===id);el.setAttribute('aria-pressed',String(el.dataset.effect===id));});preview();}
function makeEffectButton(id,item,tile){const info=effects[id]||{title:item.name,name:item.name,note:'自定义动画',icon:'spark',color:'#9180aa',soft:'#f2eef7'},button=document.createElement('button');button.className=tile?'animation-tile':'state-option';button.dataset.effect=id;button.style.setProperty('--state-color',info.color);button.style.setProperty('--state-soft',info.soft);const symbol=document.createElement('span');symbol.className=tile?'tile-symbol':'';symbol.innerHTML=svg(info.icon);const text=document.createElement('span'),name=document.createElement('strong'),note=document.createElement('small');name.textContent=tile?info.name:info.title;note.textContent='';note.hidden=true;text.append(name,note);button.append(symbol,text);button.onclick=()=>selectEffect(id);button.setAttribute('aria-label','预览'+info.title);return button;}
for(const id of ['busy','done','error','waiting'])$('quick-states').append(makeEffectButton(id,{},false));
async function loadLibrary(){library=await request('/animations');$('animation-library').replaceChildren(...library.map(a=>makeEffectButton(a.id,a,true)));all('.nav-count').forEach(el=>el.textContent=String(library.length).padStart(2,'0'));$('animation-mappings').replaceChildren();for(const id of ['busy','done','error','waiting']){const label=document.createElement('label');label.textContent=effects[id].title;const select=document.createElement('select');select.className='select';select.dataset.map=id;select.setAttribute('aria-label',effects[id].title+'灯效');for(const a of library)select.add(new Option(a.name,a.id));select.value=appInfo?.settings.stateAnimations[id]||id;select.onchange=()=>saveSetting({stateAnimations:{[id]:select.value}});label.append(select);$('animation-mappings').append(label);}selectEffect(selected);}
async function preview(){if(previewPending||document.hidden||!['overview','lighting'].includes(currentPage)||stopped)return;previewPending=true;const id=selected;try{const data=await request('/catalog-preview?id='+encodeURIComponent(id)+'&ms='+Math.floor((performance.now()-previewStart)%86400000));if(id!==selected)return;window.yogoModel?.setFrame(data.pixels,data.keys);for(const matrix of [$('large-matrix')])data.pixels.forEach((p,i)=>{const peak=Math.max(...p);matrix.children[i].style.setProperty('--pixel-rgb',p.map(n=>peak?Math.round(n/peak*255):0).join(' '));matrix.children[i].style.setProperty('--pixel-opacity',Math.pow(peak/255,.7).toFixed(3));});all('[data-led]').forEach(el=>{const p=data.keys[Number(el.dataset.led)]||[0,0,0];el.style.setProperty('--key-light',`rgb(${p.join(',')})`);});}catch{}finally{previewPending=false;}}
async function saveSetting(patch){const ok=await act('/settings',patch,'设置已保存');if(!ok)await refreshInfo();return ok;}
all('[data-setting]').forEach(el=>el.onclick=async()=>{el.disabled=true;try{await saveSetting({[el.dataset.setting]:el.getAttribute('aria-checked')!=='true'});}finally{el.disabled=false;}});$('theme').onchange=()=>saveSetting({theme:$('theme').value});$('duration').onchange=()=>saveSetting({resultDisplayMs:Number($('duration').value)});
for(const id of ['refresh','reconnect','setup-reconnect'])$(id).onclick=async()=>{await refreshInfo();await poll();toast(appInfo?.devices.length?'已识别键盘接口':'仍未检测到键盘，请检查连接和电量。');};
$('follow-toggle').onclick=()=>act(lastStatus?.mode==='auto'?'/stop':'/auto',{},lastStatus?.mode==='auto'?'已暂停灯效跟随，恢复键盘原显示':'已恢复自动跟随');$('resume-auto').onclick=()=>act('/auto',{},'已恢复自动跟随');$('play-device').onclick=()=>act('/state',{state:selected},'已切换到键盘试播，完成后可恢复自动跟随');$('preview-voice').onclick=()=>{selectEffect('voice');go('overview');$('keyboard-viewer').scrollIntoView({block:'center',behavior:document.documentElement.classList.contains('reduce-motion')?'instant':'smooth'});};
function confirmDialog(title,copy,label='确认',extra){const dlg=$('dialog');if(dlg.open)dlg.close();setText('dialog-title',title);setText('dialog-copy',copy);setText('dialog-confirm',label);$('dialog-extra').replaceChildren();if(extra)$('dialog-extra').append(extra);return new Promise(resolve=>{let done=false;const close=value=>{if(done)return;done=true;dlg.close();resolve(value);};$('dialog-confirm').onclick=()=>close(true);$('dialog-cancel').onclick=()=>close(false);$('dialog-close').onclick=()=>close(false);dlg.oncancel=()=>close(false);dlg.showModal();$('dialog-cancel').focus();});}
$('import-animation').onclick=()=>$('animation-file').click();$('animation-file').onchange=async()=>{const file=$('animation-file').files[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('动画文件不能超过 2 MB');const data=JSON.parse(await file.text());if(await act('/import-animation',data,'动画已导入')){await loadLibrary();selectEffect(data.id);}}catch(error){toast('导入失败：'+error.message,true);}finally{$('animation-file').value='';}};
$('finish-setup').onclick=async()=>{if(await saveSetting({onboardingComplete:true}))go('overview');};
$('setup-hooks').onclick=async()=>{if(window.yogoDesktop){if(await confirmDialog('设置 Codex 显示钩子？','将备份现有 hooks 配置并加入本应用的状态通知。已有的其他钩子会保留。\n随后仍需你在 Codex /hooks 中审阅和信任；应用不会自动代你授权。','写入显示钩子')){try{const result=await window.yogoDesktop.setupHooks();setText('hooks-status',result.message);toast(result.message);}catch(e){toast(e.message,true);}}}else{await confirmDialog('显示钩子的首次设置','源码版：运行项目中的 setup-hooks.cmd（Windows），或 node scripts/setup-hooks.cjs（Mac），按提示在 Codex /hooks 中审阅。\n桌面版可直接在这里写入配置，再由你完成审阅。','知道了');}};
$('open-permissions').onclick=async()=>{if(window.yogoDesktop)await window.yogoDesktop.openPermissions();else toast('打开系统设置 → 隐私与安全性 → 辅助功能 / 输入监控。');};
$('open-data').onclick=async()=>{try{if(window.yogoDesktop)await window.yogoDesktop.openData();else await confirmDialog('本地数据','源码版的数据位于项目的 .local 文件夹，设置位于 config.json。旧版键位备份仍保留在 .local/keymap-backups。','知道了');}catch(e){toast(e.message,true);}};
$('quit').onclick=async()=>{if(await confirmDialog('退出 YOGO Studio？','将停止波轮、语音和任务联动，并尝试恢复键盘原来的显示。','退出应用')){if(window.yogoDesktop)await window.yogoDesktop.quit();else{const ok=await act('/shutdown',{},'应用已退出');if(ok){stopped=true;$('service-alert').hidden=false;setText('service-alert','应用已退出，可关闭这个窗口。');setText('service-label','已退出');}}}};
async function boot(){try{await refreshInfo();await loadLibrary();await poll();if(window.yogoDesktop){const info=await window.yogoDesktop.info();$('login-item-row').hidden=!info.packaged;$('login-item').setAttribute('aria-checked',String(info.openAtLogin));$('login-item').onclick=async()=>{try{const value=$('login-item').getAttribute('aria-checked')!=='true';await window.yogoDesktop.setLogin(value);$('login-item').setAttribute('aria-checked',String(value));toast('启动偏好已保存');}catch(e){toast(e.message,true);}};}else setText('tray-explanation','关闭网页后继续运行，退出才停止联动。');}catch(error){toast(error.message,true);}}
let scopeSelecting=false;
async function loadSessions(){const items=await request('/sessions');$('session-select').replaceChildren(new Option('请选择本地任务',''));for(const item of items)$('session-select').add(new Option(new Date(item.modified).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})+' · '+item.id,item.id));$('session-select').value=appInfo?.settings.sessionId||'';}
$('scope').onchange=async()=>{if($('scope').value==='global'){scopeSelecting=false;await act('/scope',{scope:'global'},'已跟随全部本地任务');}else{scopeSelecting=true;$('session-row').hidden=false;try{await loadSessions();}catch(error){toast(friendlyError(error.message),true);scopeSelecting=false;await refreshInfo();}}};
$('session-select').onchange=async()=>{if(!$('session-select').value)return;if(await act('/scope',{scope:'current',sessionId:$('session-select').value},'已切换到指定任务'))scopeSelecting=false;};
boot().then(()=>{if(appInfo?.settings.scope==='current')loadSessions().catch(()=>{});});setInterval(poll,1400);setInterval(refreshInfo,6000);setInterval(preview,110);
